version: "3"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-dev1
    ports:
      - "5173:80"
    volumes:
      - ./client:/front:cached 


networks:

  default:
    attachable: true
