version: "3"
services:
 
  server:
    build:
      context: ./server
    ports:
      - "80:80"
    volumes:
      - ./server:/workspace:cached 
    environment:
      - SOME_ENV=HELLOOOO
    privileged: true
    container_name: chronos-Backend-Dev

  frontend:
    image: node:18-alpine

    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:80"
    volumes:
      - ./client:/workspace/frontend:cached
       - /workspace/frontend/node_modules

networks:

  default:
    attachable: true
