version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "80:80"
    volumes:
      - ./server:/workspace:cached 
    environment:
      - SOME_ENV=HELLOOOO
    privileged: true
    container_name: chronos-Backend-Dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:80"
    volumes:
      - ./client:/workspace:cached 

networks:

  default:
    attachable: true
