version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "80:80"
    volumes:
      - ./server:/workspace:cached 
    environment:
      - SOME_ENV=HELLOOOO
    privileged: true
    container_name: chronos-Backend-Dev

networks:

  default:
    attachable: true
